NosCoreIO/NosCore

NosCore.sln
src/NosCore.GameObject/Character.cs
src/NosCore.GameObject/ComponentEntities/Extensions/AliveEntityExtension.cs
src/NosCore.GameObject/Map/Maps.cs
src/NosCore.GameObject/MapInstance.cs
src/NosCore.GameObject/Networking/BroadcastPacket.cs
src/NosCore.GameObject/Networking/BroadcastableBase.cs
src/NosCore.GameObject/NosCore.GameObject.csproj
src/NosCore.Handler/DefaultPacketHandler.cs
src/NosCore.MasterServer/NosCore.MasterServer.csproj
src/NosCore.Packets/ClientPackets/WalkPacket.cs
src/NosCore.Packets/ServerPackets/MovePacket.cs
src/NosCore.PathFinder/Heuristic.cs
src/NosCore.PathFinder/NosCore.PathFinder.csproj
src/NosCore.WorldServer/NosCore.WorldServer.csproj

Implemented:
Walk System
Broadcast System
PathFinder System

Implement Walk System

---

src/NosCore.GameObject/ComponentEntities/Extensions/AliveEntityExtension.cs
src/NosCore.Handler/DefaultPacketHandler.cs
src/NosCore.Packets/ClientPackets/GuriPacket.cs
src/NosCore.Packets/ServerPackets/EffectPacket.cs

Implent guri packet

---

src/NosCore.Domain/SayColorType.cs
src/NosCore.GameObject/ComponentEntities/Extensions/AliveEntityExtension.cs
src/NosCore.Handler/DefaultPacketController.cs
src/NosCore.Packets/ServerPackets/SayPacket.cs

added enum for SayPacker color and replaced all say color with this the enum

[ADD] enum for SayPacket color #74

---

src/NosCore.Core/Resource/LocalizedResources.fr.resx

Add part of French LocalizedRessources

---

src/NosCore.Core/Resource/LocalizedResources.fr.resx

Added last translation into LocalizationResource.fr

Last french translation

---

src/NosCore.Core/Resource/LocalizedResources.pl.resx

I add LocalizedResources.pl translation

Update Polish LocalizedResources

---

src/NosCore.Core/Resource/LocalizedResources.pl.resx

I add 3 new values 
value #<PARSE_ITEMS> 
value #<SELECT_MAPID>
value #<WRONG_SELECTED_MAPID>

Update Polish LocalizedResources v2

---

src/NosCore.Shared/Resource/LocalizedResources.cs.resx

Added Missing translate
Update Old and Wrong Translate

Update CS Language

---

src/NosCore.Controllers/CommandPacketController.cs
src/NosCore.Controllers/InventoryPacketController.cs
src/NosCore.GameObject/Inventory.cs
src/NosCore.Packets/ClientPackets/MviPacket.cs
test/NosCore.Tests/InventoryTests.cs

Add inventory move

---

src/NosCore.Shared/Resource/LocalizedResources.fr.resx

Update French LocalizedResources

---

src/NosCore.Shared/Resource/LocalizedResources.es.resx

Sorry, I love making the translations perfect xD (It will not be perfect, but better than NosTale oficial Spanish Translation, I hope).

Minor fixes

---

src/NosCore.Configuration/LanguageConfiguration.cs
src/NosCore.Controllers/CharacterScreenPacketController.cs
src/NosCore.Core/Encryption/LoginEncoder.cs
src/NosCore.Core/Encryption/WorldDecoder.cs
src/NosCore.Core/Encryption/WorldEncoder.cs
src/NosCore.Core/Extensions/RegionTypeExtension.cs
src/NosCore.Core/Networking/SessionFactory.cs
src/NosCore.Core/NosCore.Core.csproj
src/NosCore.GameObject/Networking/ClientSession.cs
src/NosCore.GameObject/Networking/PipelineFactory.cs
src/NosCore.Shared/I18N/LanguageKey.cs
src/NosCore.Shared/I18N/LogLanguage.cs
src/NosCore.Shared/RegionTypeMapping.cs

add multi culture

---

src/NosCore.Shared/Resource/LocalizedResources.es.resx

Update some Spanish LocalizedResourcesEs

---

src/NosCore.GameObject/Networking/Broadcaster.cs
src/NosCore.GameObject/Networking/ClientSession/ClientSession.cs
src/NosCore.GameObject/Services/PortalGeneration/Portal.cs
src/NosCore.Parser/Parsers/I18NParser.cs
src/NosCore.WorldServer/Startup.cs
test/NosCore.Tests/HandlerTests/DefaultPacketControllerTests.cs

add test preq

---

src/NosCore.Shared/Resource/LocalizedResources.fr.resx

May have some little errors yet but everything is now translated, at least.

French Localization

---

src/NosCore.Packets/ClientPackets/LbsPacket.cs

Add missing packets

---

src/NosCore.Shared/Resource/LocalizedResources.fr.resx

French Translation update

---

src/NosCore.Controllers/CommandPacketController.cs
src/NosCore.Controllers/DefaultPacketController.cs
src/NosCore.Core/Networking/WebApiAccess.cs
src/NosCore.Data/WebApi/StatData.cs
src/NosCore.GameObject/Character.cs
src/NosCore.GameObject/ComponentEntities/Interfaces/ICharacterEntity.cs
src/NosCore.Packets/CommandPackets/SetHeroLevelCommandPacket.cs
src/NosCore.Packets/CommandPackets/SetJobLevelCommandPacket.cs
src/NosCore.Packets/CommandPackets/SetLevelCommandPacket.cs
src/NosCore.Shared/Enumerations/UpdateStatActionType.cs
src/NosCore.Shared/I18N/LanguageKey.cs
src/NosCore.Shared/Resource/LocalizedResources.fr.resx
src/NosCore.WorldServer/Controllers/PacketController.cs
src/NosCore.WorldServer/Controllers/RelationController.cs
src/NosCore.WorldServer/Controllers/StatController.cs

Take care luci i'll take your job soon.

Level, JobLevel & HeroLevel commands #305

---

src/NosCore.Shared/Resource/LocalizedResources.fr.resx

Some translations are missing (see comment box)

French Localization update

---

src/NosCore.Shared/Resource/LocalizedResources.fr.resx

Thanks Adanlink for stings context.

French Localization update 2

---

src/NosCore.Shared/Resource/LocalizedResources.Designer.cs
src/NosCore.Shared/Resource/LocalizedResources.resx

Update EN Data

---

.travis.yml

should speed up your build a little

dont build as part of test

---

src/NosCore.Shared/Resource/LocalizedResources.fr.resx

Update Localization FR

---

src/NosCore.GameObject/Networking/ClientSession/ClientSession.cs

Fix usage of pst packet

---

src/NosCore.Controllers/DefaultPacketController.cs

Fix usage of cond packet

---

src/NosCore.Data/Resource/LocalizedResources.ru.resx

Untranslated entries was deleted

Updated Russian translation

---

src/NosCore.GameObject/Providers/NRunProvider/Handlers/TeleporterHandler.cs

Warp Towers of NosVille, Krem and Port Alveus now work with they respective price.

TeleporterHandler added

---

src/NosCore.Controllers/Bazaar/CSkillPacketHandler.cs
src/NosCore.Data/Enumerations/I18N/LanguageKey.cs
src/NosCore.Data/Resource/LocalizedResources.pl.resx

+ NO_BAZAAR_MEDAL 
+ missing PL keys

add NO_BAZAAR_MEDAL key, add missing PL keys

---

src/NosCore.Controllers/Exchange/ExchangeRequestPacketHandler.cs
src/NosCore.Data/Resource/LocalizedResources.Designer.cs
src/NosCore.Data/Resource/LocalizedResources.cs.resx
src/NosCore.Data/Resource/LocalizedResources.de.resx
src/NosCore.Data/Resource/LocalizedResources.fr.resx
src/NosCore.Data/Resource/LocalizedResources.it.resx
src/NosCore.Data/Resource/LocalizedResources.pl.resx
src/NosCore.Data/Resource/LocalizedResources.resx

Player name in exchange

---

src/NosCore.Controllers/Exchange/ExchangeRequestPacketHandler.cs
src/NosCore.Data/Resource/LocalizedResources.Designer.cs
src/NosCore.Data/Resource/LocalizedResources.de.resx
src/NosCore.Data/Resource/LocalizedResources.fr.resx
src/NosCore.Data/Resource/LocalizedResources.resx
test/NosCore.Tests/LogLanguageTests.cs

Add translation

---

src/NosCore.Database/Entities/EquipmentOption.cs
src/NosCore.Database/Migrations/20190924031848_Aphrodite6.Designer.cs
src/NosCore.Database/Migrations/20190924031848_Aphrodite6.cs
src/NosCore.Database/ModelBuilderExtensions.cs

https://github.com/aspnet/EntityFrameworkCore/issues/18006

Fix tph naming

---

.dockerignore
README.md
deploy/Dockerfile-login
deploy/Dockerfile-master
deploy/Dockerfile-world
docker-compose.yml
src/NosCore.Core/I18N/Logger.cs
src/NosCore.LoginServer/NosCore.LoginServer.csproj

Containerization

---

src/NosCore.Controllers/Group/PjoinPacketHandler.cs

Little bug "to pick" issue :
https://github.com/NosCoreIO/NosCore/issues/517

Fix issue #517 : Group request persist

---

src/NosCore.Controllers/Group/PjoinPacketHandler.cs
src/NosCore.Data/Enumerations/I18N/LanguageKey.cs
src/NosCore.Data/Resource/LocalizedResources.Designer.cs
src/NosCore.Data/Resource/LocalizedResources.fr.resx
src/NosCore.Data/Resource/LocalizedResources.resx
src/NosCore.GameObject/Character.cs
test/NosCore.Tests/PacketHandlerTests/PJoinPacketHandlerTests.cs

Add a delay of 5 seconds on group request

Fix issue #518 : Add delay for group requests

---

src/NosCore.Data/Resource/LocalizedResources.de.resx

[VION#1023] Translation [DE]

---

src/NosCore.Database/Migrations/20200223222340_Aphrodite4.Designer.cs
src/NosCore.Database/Migrations/20200223222340_Aphrodite4.cs
src/NosCore.Database/NosCoreContext.cs

some tables has duplicated foreign keys and fields (like NpcMonsterVNum and SkillVNum)

fix duplicated foreign keys

---

src/NosCore.Data/Resource/LocalizedResources.it.resx

Update Italian LocalizedResources

[Limo] Translation [IT]

---

src/NosCore.Data/Resource/LocalizedResources.tr.resx

[serodyx] Translation [TR]

---

src/NosCore.Core/Controllers/AuthController.cs
src/NosCore.Core/NosCore.Core.csproj
src/NosCore.Data/Dto/Entities/AccountDto.generated.cs
src/NosCore.Data/Enumerations/I18N/LanguageKey.cs
src/NosCore.Database/Entities/Account.cs
src/NosCore.Database/Migrations/20201128030127_Aphrodite3.Designer.cs
src/NosCore.Database/Migrations/20201128030127_Aphrodite3.cs
src/NosCore.GameObject/Networking/ClientSession/ClientSession.cs
src/NosCore.GameObject/Networking/LoginService/LoginService.cs
src/NosCore.GameObject/Providers/GuriProvider/Handlers/MfaGuriHandler.cs
src/NosCore.GameObject/Providers/GuriProvider/Handlers/SpeakerGuriHandler.cs
src/NosCore.PacketHandlers/CharacterScreen/EntryPointPacketHandler.cs
test/NosCore.Tests/ApiTests/AuthControllerTests.cs
test/NosCore.Tests/Helpers/TestHelpers.cs
test/NosCore.Tests/PacketHandlerTests/NoS0577PacketHandlerTests.cs

Start adding mfa
